Characters cannot be created with empty name
lotgd/crate-graphql pull request #39
Opened 2017-05-25 10:53 UTC by Vassyli

Additionally, character names not containing letters and spaces only are
rejected as well.

Fixes #36

2017-05-25 23:56 UTC, austenmc requested changes

2017-05-25 23:56 UTC, austenmc commented on src/Services/CharacterManagerService.php
> +        $name_sanitized = preg_replace("/[^\\p{L} ]/u", "", $name);
I dont think this restriction is a good idea.

There are plenty of reasonable characters this excludes, like '",|()*^@... For sure we should allow some of those if not all symbols.

It also doesnt allow any emoji, which I think a modern game should allow. Can you dig around for a regexp that covers most reasonable "character-like" things? So everything but control characters I suppose, like ^A etc.

2017-05-26 07:59 UTC, Vassyli commented on src/Services/CharacterManagerService.php
> +        $name_sanitized = preg_replace("/[^\\p{L} ]/u", "", $name);
Done, it's simply p{C}.

2017-05-26 07:59 UTC, Vassyli commented
Changes applied, please approve.

2017-06-07 09:23 UTC, merged