Adds public and private character stats that can be used via events
lotgd/crate-graphql pull request #43
Opened 2018-04-16 11:39 UTC by Vassyli

This PR updates dependencies and adds public and private character stats. Public character stats can be pulled for a "list of fighters", private ones for "current character stats", to be used during scene changes, for example.

2018-04-17 04:34 UTC, austenmc requested changes
In general this looks good, but Im not sure how useful the distinction between public and private stats are. Why not just have "stats" and then the system returns all the stats you are authorized to see?

Added some small nits and suggestions as well.

2018-04-17 04:34 UTC, austenmc commented on app/config/config.yml
> +        #internal_error_message: "An error occurred, please retry later or contact us!"
Can we not have comments?

2018-04-17 04:34 UTC, austenmc commented on app/config/routing.yml
> +#overblog_graphql_graphiql:
Do we really need comments here? We should just remove the code and keep it in the git history if we need it.

2018-04-17 04:34 UTC, austenmc commented on src/AppBundle/GraphQL/Types/CharacterType.php
> +    public function getPrivateStats(): array
I dont like that getPrivateStats() returns both public and private. Either change it to getPublicAndPrivateStats or have it return only the private stats.

2018-04-17 04:34 UTC, austenmc commented on src/AppBundle/GraphQL/Types/CharacterType.php
> +        $stats = [
nit: remove newline

2018-04-17 06:25 UTC, Vassyli commented
Yeah, that's a good suggestion. I'll look into changing it to "stats", which gets rows from `getPublicStats()` and, if the character is authorized, `getPrivateStats()`.

2018-04-18 08:42 UTC, Vassyli commented
Done.

2018-04-18 20:07 UTC, austenmc commented
Looks good. Let’s merge.

2018-04-23 08:01 UTC, merged